FROM alpine:3.24@sha256:d56c381f961d307a21b3ca004cf1e3910f106644aefb1f43e654c8a56c4fd395

LABEL maintainer="Thorsten Schifferdecker https://github.com/curx" \
  org.label-schema.vendor="Thorsten Schifferdecker" \
  org.label-schema.name="git" \
  org.label-schema.version="1.1" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/git"]
CMD ["--help"]

RUN apk -U --no-cache add git

WORKDIR /data
