FROM alpine:3.18@sha256:34871e7290500828b39e22294660bee86d966bc0017544e848dd9a255cdf59e0

LABEL maintainer="Thorsten Schifferdecker https://github.com/curx" \
  org.label-schema.vendor="Thorsten Schifferdecker" \
  org.label-schema.name="git" \
  org.label-schema.version="1.1" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/git"]
CMD ["--help"]

RUN apk -U --no-cache add git

WORKDIR /data
