FROM arm64v8/alpine:3.19@sha256:a0264d60f80df12bc1e6dd98bae6c43debe6667c0ba482711f0d806493467a46

LABEL maintainer="Thorsten Schifferdecker https://github.com/curx" \
  org.label-schema.vendor="Thorsten Schifferdecker" \
  org.label-schema.name="git" \      
  org.label-schema.version="1.1" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/git"]
CMD ["--help"]

RUN apk -U --no-cache add git

WORKDIR /data
