FROM arm32v6/alpine:3.24@sha256:d3c3fda3e4d3f0fcfc86cf469c6dfbe65017143dde23feb4b11df37c373cdc76

LABEL maintainer="Thorsten Schifferdecker https://github.com/curx" \
  org.label-schema.vendor="Thorsten Schifferdecker" \
  org.label-schema.name="git" \      
  org.label-schema.version="1.1" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/git"]
CMD ["--help"]

RUN apk -U --no-cache add git

WORKDIR /data
